spring:
  datasource:
    #    url: jdbc:mysql://129.154.58.221:3306/book_db
    url: jdbc:mysql://192.168.2.101:3306/todo1
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5        # ??? ?? 30?? ??
      minimum-idle: 2             # ???? ?? ??? ??? ???? ?? (5?)
      idle-timeout: 30000         # ???? ?? ??? ?? ?? (5?)
      max-lifetime: 30000         # ??? ???? ?? ?? ?? (5?)
      connection-timeout: 30000   # ??? ?? ? ???? ?? ?? ?? ???? (5?)
    username: root
    password: 1q2w3e4r!@

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true